app = "user-frontend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    context = "."

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0